/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ScanId = IDL.Nat;
export const DRStage = IDL.Variant({
  'Mild' : IDL.Null,
  'Proliferative' : IDL.Null,
  'Severe' : IDL.Null,
  'Moderate' : IDL.Null,
  'NoRetinopathy' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Moderate' : IDL.Null,
});
export const ClassificationResult = IDL.Record({
  'stage' : DRStage,
  'confidence' : IDL.Float64,
  'riskLevel' : RiskLevel,
  'heatmapImageUrl' : IDL.Text,
});
export const PatientId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const ScanRecord = IDL.Record({
  'id' : ScanId,
  'result' : IDL.Opt(ClassificationResult),
  'patientId' : PatientId,
  'shareToken' : IDL.Opt(IDL.Text),
  'imageId' : ExternalBlob,
  'uploadedAt' : Timestamp,
});
export const Result_2 = IDL.Variant({ 'ok' : ScanRecord, 'err' : IDL.Text });
export const DiabetesType = IDL.Variant({
  'Gestational' : IDL.Null,
  'None' : IDL.Null,
  'Type1' : IDL.Null,
  'Type2' : IDL.Null,
});
export const CreatePatientInput = IDL.Record({
  'age' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'hbA1c' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'diabetesType' : DiabetesType,
});
export const Patient = IDL.Record({
  'id' : PatientId,
  'age' : IDL.Nat,
  'principal' : IDL.Principal,
  'contactInfo' : IDL.Text,
  'hbA1c' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'diabetesType' : DiabetesType,
  'updatedAt' : Timestamp,
});
export const Result = IDL.Variant({ 'ok' : Patient, 'err' : IDL.Text });
export const CreateScanInput = IDL.Record({ 'imageId' : ExternalBlob });
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const SharedScanView = IDL.Record({
  'result' : IDL.Opt(ClassificationResult),
  'scanId' : ScanId,
  'uploadedAt' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdatePatientInput = IDL.Record({
  'age' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'hbA1c' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'diabetesType' : DiabetesType,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'classifyScan' : IDL.Func([ScanId], [Result_2], []),
  'createProfile' : IDL.Func([CreatePatientInput], [Result], []),
  'createScan' : IDL.Func([CreateScanInput], [Result_2], []),
  'generateShareToken' : IDL.Func([ScanId], [Result_1], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Patient)], ['query']),
  'getMyScans' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'getScan' : IDL.Func([ScanId], [IDL.Opt(ScanRecord)], ['query']),
  'getSharedScan' : IDL.Func([IDL.Text], [IDL.Opt(SharedScanView)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProfile' : IDL.Func([UpdatePatientInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ScanId = IDL.Nat;
  const DRStage = IDL.Variant({
    'Mild' : IDL.Null,
    'Proliferative' : IDL.Null,
    'Severe' : IDL.Null,
    'Moderate' : IDL.Null,
    'NoRetinopathy' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Moderate' : IDL.Null,
  });
  const ClassificationResult = IDL.Record({
    'stage' : DRStage,
    'confidence' : IDL.Float64,
    'riskLevel' : RiskLevel,
    'heatmapImageUrl' : IDL.Text,
  });
  const PatientId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const ScanRecord = IDL.Record({
    'id' : ScanId,
    'result' : IDL.Opt(ClassificationResult),
    'patientId' : PatientId,
    'shareToken' : IDL.Opt(IDL.Text),
    'imageId' : ExternalBlob,
    'uploadedAt' : Timestamp,
  });
  const Result_2 = IDL.Variant({ 'ok' : ScanRecord, 'err' : IDL.Text });
  const DiabetesType = IDL.Variant({
    'Gestational' : IDL.Null,
    'None' : IDL.Null,
    'Type1' : IDL.Null,
    'Type2' : IDL.Null,
  });
  const CreatePatientInput = IDL.Record({
    'age' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'hbA1c' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'diabetesType' : DiabetesType,
  });
  const Patient = IDL.Record({
    'id' : PatientId,
    'age' : IDL.Nat,
    'principal' : IDL.Principal,
    'contactInfo' : IDL.Text,
    'hbA1c' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'diabetesType' : DiabetesType,
    'updatedAt' : Timestamp,
  });
  const Result = IDL.Variant({ 'ok' : Patient, 'err' : IDL.Text });
  const CreateScanInput = IDL.Record({ 'imageId' : ExternalBlob });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const SharedScanView = IDL.Record({
    'result' : IDL.Opt(ClassificationResult),
    'scanId' : ScanId,
    'uploadedAt' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdatePatientInput = IDL.Record({
    'age' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'hbA1c' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'diabetesType' : DiabetesType,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'classifyScan' : IDL.Func([ScanId], [Result_2], []),
    'createProfile' : IDL.Func([CreatePatientInput], [Result], []),
    'createScan' : IDL.Func([CreateScanInput], [Result_2], []),
    'generateShareToken' : IDL.Func([ScanId], [Result_1], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Patient)], ['query']),
    'getMyScans' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'getScan' : IDL.Func([ScanId], [IDL.Opt(ScanRecord)], ['query']),
    'getSharedScan' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SharedScanView)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProfile' : IDL.Func([UpdatePatientInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };