/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClassificationResult {
  'stage' : DRStage,
  'confidence' : number,
  'riskLevel' : RiskLevel,
  'heatmapImageUrl' : string,
}
export interface CreatePatientInput {
  'age' : bigint,
  'contactInfo' : string,
  'hbA1c' : [] | [number],
  'name' : string,
  'diabetesType' : DiabetesType,
}
export interface CreateScanInput { 'imageId' : ExternalBlob }
export type DRStage = { 'Mild' : null } |
  { 'Proliferative' : null } |
  { 'Severe' : null } |
  { 'Moderate' : null } |
  { 'NoRetinopathy' : null };
export type DiabetesType = { 'Gestational' : null } |
  { 'None' : null } |
  { 'Type1' : null } |
  { 'Type2' : null };
export type ExternalBlob = Uint8Array;
export interface Patient {
  'id' : PatientId,
  'age' : bigint,
  'principal' : Principal,
  'contactInfo' : string,
  'hbA1c' : [] | [number],
  'name' : string,
  'createdAt' : Timestamp,
  'diabetesType' : DiabetesType,
  'updatedAt' : Timestamp,
}
export type PatientId = bigint;
export type Result = { 'ok' : Patient } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type Result_2 = { 'ok' : ScanRecord } |
  { 'err' : string };
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Moderate' : null };
export type ScanId = bigint;
export interface ScanRecord {
  'id' : ScanId,
  'result' : [] | [ClassificationResult],
  'patientId' : PatientId,
  'shareToken' : [] | [string],
  'imageId' : ExternalBlob,
  'uploadedAt' : Timestamp,
}
export interface SharedScanView {
  'result' : [] | [ClassificationResult],
  'scanId' : ScanId,
  'uploadedAt' : Timestamp,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdatePatientInput {
  'age' : bigint,
  'contactInfo' : string,
  'hbA1c' : [] | [number],
  'name' : string,
  'diabetesType' : DiabetesType,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'classifyScan' : ActorMethod<[ScanId], Result_2>,
  'createProfile' : ActorMethod<[CreatePatientInput], Result>,
  'createScan' : ActorMethod<[CreateScanInput], Result_2>,
  'generateShareToken' : ActorMethod<[ScanId], Result_1>,
  'getMyProfile' : ActorMethod<[], [] | [Patient]>,
  'getMyScans' : ActorMethod<[], Array<ScanRecord>>,
  'getScan' : ActorMethod<[ScanId], [] | [ScanRecord]>,
  'getSharedScan' : ActorMethod<[string], [] | [SharedScanView]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProfile' : ActorMethod<[UpdatePatientInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];