/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UpdatePatientInput {
    age: bigint;
    contactInfo: string;
    hbA1c?: number;
    name: string;
    diabetesType: DiabetesType;
}
export type Result_2 = {
    __kind__: "ok";
    ok: ScanRecord;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SharedScanView {
    result?: ClassificationResult;
    scanId: ScanId;
    uploadedAt: Timestamp;
}
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ScanRecord {
    id: ScanId;
    result?: ClassificationResult;
    patientId: PatientId;
    shareToken?: string;
    imageId: ExternalBlob;
    uploadedAt: Timestamp;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type PatientId = bigint;
export type Result = {
    __kind__: "ok";
    ok: Patient;
} | {
    __kind__: "err";
    err: string;
};
export interface Patient {
    id: PatientId;
    age: bigint;
    principal: Principal;
    contactInfo: string;
    hbA1c?: number;
    name: string;
    createdAt: Timestamp;
    diabetesType: DiabetesType;
    updatedAt: Timestamp;
}
export type ScanId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CreateScanInput {
    imageId: ExternalBlob;
}
export interface ClassificationResult {
    stage: DRStage;
    confidence: number;
    riskLevel: RiskLevel;
    heatmapImageUrl: string;
}
export interface CreatePatientInput {
    age: bigint;
    contactInfo: string;
    hbA1c?: number;
    name: string;
    diabetesType: DiabetesType;
}
export enum DRStage {
    Mild = "Mild",
    Proliferative = "Proliferative",
    Severe = "Severe",
    Moderate = "Moderate",
    NoRetinopathy = "NoRetinopathy"
}
export enum DiabetesType {
    Gestational = "Gestational",
    None = "None",
    Type1 = "Type1",
    Type2 = "Type2"
}
export enum RiskLevel {
    Low = "Low",
    High = "High",
    Moderate = "Moderate"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    classifyScan(scanId: ScanId): Promise<Result_2>;
    createProfile(input: CreatePatientInput): Promise<Result>;
    createScan(input: CreateScanInput): Promise<Result_2>;
    generateShareToken(scanId: ScanId): Promise<Result_1>;
    getMyProfile(): Promise<Patient | null>;
    getMyScans(): Promise<Array<ScanRecord>>;
    getScan(scanId: ScanId): Promise<ScanRecord | null>;
    getSharedScan(token: string): Promise<SharedScanView | null>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateProfile(input: UpdatePatientInput): Promise<Result>;
}
import type { ClassificationResult as _ClassificationResult, CreatePatientInput as _CreatePatientInput, CreateScanInput as _CreateScanInput, DRStage as _DRStage, DiabetesType as _DiabetesType, ExternalBlob as _ExternalBlob, Patient as _Patient, PatientId as _PatientId, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, RiskLevel as _RiskLevel, ScanId as _ScanId, ScanRecord as _ScanRecord, SharedScanView as _SharedScanView, Timestamp as _Timestamp, UpdatePatientInput as _UpdatePatientInput, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async classifyScan(arg0: ScanId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.classifyScan(arg0);
                return from_candid_Result_2_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.classifyScan(arg0);
            return from_candid_Result_2_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: CreatePatientInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(to_candid_CreatePatientInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(to_candid_CreatePatientInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createScan(arg0: CreateScanInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createScan(await to_candid_CreateScanInput_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScan(await to_candid_CreateScanInput_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateShareToken(arg0: ScanId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.generateShareToken(arg0);
                return from_candid_Result_1_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateShareToken(arg0);
            return from_candid_Result_1_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyScans(): Promise<Array<ScanRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyScans();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyScans();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScan(arg0: ScanId): Promise<ScanRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScan(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScan(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedScan(arg0: string): Promise<SharedScanView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedScan(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedScan(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateProfile(arg0: UpdatePatientInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdatePatientInput_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdatePatientInput_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ClassificationResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassificationResult): ClassificationResult {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DRStage_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DRStage): DRStage {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DiabetesType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiabetesType): DiabetesType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Patient_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_Result_2_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Promise<Result_2> {
    return await from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ScanRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanRecord): Promise<ScanRecord> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SharedScanView_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SharedScanView): SharedScanView {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClassificationResult]): ClassificationResult | null {
    return value.length === 0 ? null : from_candid_ClassificationResult_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : from_candid_Patient_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScanRecord]): Promise<ScanRecord | null> {
    return value.length === 0 ? null : await from_candid_ScanRecord_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SharedScanView]): SharedScanView | null {
    return value.length === 0 ? null : from_candid_SharedScanView_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScanId;
    result: [] | [_ClassificationResult];
    patientId: _PatientId;
    shareToken: [] | [string];
    imageId: _ExternalBlob;
    uploadedAt: _Timestamp;
}): Promise<{
    id: ScanId;
    result?: ClassificationResult;
    patientId: PatientId;
    shareToken?: string;
    imageId: ExternalBlob;
    uploadedAt: Timestamp;
}> {
    return {
        id: value.id,
        result: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.result)),
        patientId: value.patientId,
        shareToken: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.shareToken)),
        imageId: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.imageId),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stage: _DRStage;
    confidence: number;
    riskLevel: _RiskLevel;
    heatmapImageUrl: string;
}): {
    stage: DRStage;
    confidence: number;
    riskLevel: RiskLevel;
    heatmapImageUrl: string;
} {
    return {
        stage: from_candid_DRStage_n15(_uploadFile, _downloadFile, value.stage),
        confidence: value.confidence,
        riskLevel: from_candid_RiskLevel_n17(_uploadFile, _downloadFile, value.riskLevel),
        heatmapImageUrl: value.heatmapImageUrl
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PatientId;
    age: bigint;
    principal: Principal;
    contactInfo: string;
    hbA1c: [] | [number];
    name: string;
    createdAt: _Timestamp;
    diabetesType: _DiabetesType;
    updatedAt: _Timestamp;
}): {
    id: PatientId;
    age: bigint;
    principal: Principal;
    contactInfo: string;
    hbA1c?: number;
    name: string;
    createdAt: Timestamp;
    diabetesType: DiabetesType;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        age: value.age,
        principal: value.principal,
        contactInfo: value.contactInfo,
        hbA1c: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.hbA1c)),
        name: value.name,
        createdAt: value.createdAt,
        diabetesType: from_candid_DiabetesType_n30(_uploadFile, _downloadFile, value.diabetesType),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: [] | [_ClassificationResult];
    scanId: _ScanId;
    uploadedAt: _Timestamp;
}): {
    result?: ClassificationResult;
    scanId: ScanId;
    uploadedAt: Timestamp;
} {
    return {
        result: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.result)),
        scanId: value.scanId,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mild: null;
} | {
    Proliferative: null;
} | {
    Severe: null;
} | {
    Moderate: null;
} | {
    NoRetinopathy: null;
}): DRStage {
    return "Mild" in value ? DRStage.Mild : "Proliferative" in value ? DRStage.Proliferative : "Severe" in value ? DRStage.Severe : "Moderate" in value ? DRStage.Moderate : "NoRetinopathy" in value ? DRStage.NoRetinopathy : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Moderate: null;
}): RiskLevel {
    return "Low" in value ? RiskLevel.Low : "High" in value ? RiskLevel.High : "Moderate" in value ? RiskLevel.Moderate : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Patient;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Patient;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Patient_n27(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Gestational: null;
} | {
    None: null;
} | {
    Type1: null;
} | {
    Type2: null;
}): DiabetesType {
    return "Gestational" in value ? DiabetesType.Gestational : "None" in value ? DiabetesType.None : "Type1" in value ? DiabetesType.Type1 : "Type2" in value ? DiabetesType.Type2 : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ScanRecord;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: ScanRecord;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_ScanRecord_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScanRecord>): Promise<Array<ScanRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ScanRecord_n10(_uploadFile, _downloadFile, x)));
}
function to_candid_CreatePatientInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePatientInput): _CreatePatientInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateScanInput_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateScanInput): Promise<_CreateScanInput> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_DiabetesType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiabetesType): _DiabetesType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UpdatePatientInput_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePatientInput): _UpdatePatientInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    contactInfo: string;
    hbA1c?: number;
    name: string;
    diabetesType: DiabetesType;
}): {
    age: bigint;
    contactInfo: string;
    hbA1c: [] | [number];
    name: string;
    diabetesType: _DiabetesType;
} {
    return {
        age: value.age,
        contactInfo: value.contactInfo,
        hbA1c: value.hbA1c ? candid_some(value.hbA1c) : candid_none(),
        name: value.name,
        diabetesType: to_candid_DiabetesType_n23(_uploadFile, _downloadFile, value.diabetesType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageId: ExternalBlob;
}): Promise<{
    imageId: _ExternalBlob;
}> {
    return {
        imageId: await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.imageId)
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiabetesType): {
    Gestational: null;
} | {
    None: null;
} | {
    Type1: null;
} | {
    Type2: null;
} {
    return value == DiabetesType.Gestational ? {
        Gestational: null
    } : value == DiabetesType.None ? {
        None: null
    } : value == DiabetesType.Type1 ? {
        Type1: null
    } : value == DiabetesType.Type2 ? {
        Type2: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
